name: Docker CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - dev
      - main

jobs:
  build-and-push-frontend:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: [f1]
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.VERSION_TAG }}

  build-and-push-backend:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: [b1]
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "TAG_SUFFIX=prod-backend-${SHORT_SHA}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Backend1
        uses: docker/build-push-action@v5
        with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }}

      - name: Build & Push Backend2
        uses: docker/build-push-action@v5
        with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }}
