name: Docker CI

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  build-and-push-frontend:
    runs-on: [f1]
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up _diag pages
        run: |
          echo "Cleaning /home/skool/runner/actions-runner/frontend/_diag/pages"
          rm -f /home/skool/runner/actions-runner/frontend/_diag/pages/*.log || true



      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            echo "TAG_SUFFIX=$VERSION_TAG" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG_SUFFIX=$LATEST_TAG" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.TAG_SUFFIX }}

      - name: Pull frontend image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.TAG_SUFFIX }}

      - name: Save Docker image for frontend
        run: |
           docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.TAG_SUFFIX }} -o frontend.tar
      - name: Upload frontend image tar
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend.tar

  build-and-push-backend:
    runs-on: [b1]
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up _diag pages
        run: |
          echo "Cleaning /home/skool/runner/actions-runner/backend/_diag/pages"
          rm -f /home/skool/runner/actions-runner/backend/_diag/pages/*.log || true


      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            echo "TAG_SUFFIX=$VERSION_TAG" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG_SUFFIX=$LATEST_TAG" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Backend1
        uses: docker/build-push-action@v6
        with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }}

      - name: Pull backend1 image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }}

      - name: Save Docker image for backend1
        run: |
           docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }} -o backend1.tar
      - name: Upload backend1 image tar
        uses: actions/upload-artifact@v4
        with:
          name: backend1-image
          path: backend1.tar

      - name: Build & Push Backend2
        uses: docker/build-push-action@v6
        with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }}

      - name: Pull backend2 image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }}

      - name: Save Docker image for backend2
        run: |
           docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }} -o backend2.tar
      - name: Upload backend2 image tar
        uses: actions/upload-artifact@v4
        with:
          name: backend2-image
          path: backend2.tar
