name: Docker CI
permissions:
  contents: write
  issues: write
on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  build-and-push-frontend:
    runs-on: [f1]
    environment: ${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}
    steps:
      - name: Force cleanup runner workspace
        run: |
          echo "Force cleaning runner workspace..."
          
          # Clean up any existing artifacts
          rm -f frontend.tar.gz || true
          
          # Clean Docker system
          docker system prune -f || true
          
          # Clean up workspace (only files we own)
          find ${{ github.workspace }} -type f -delete || true
          find ${{ github.workspace }} -type d -empty -delete || true
        continue-on-error: true

      - name: Post-job cleanup
        if: always()
        run: |
          echo "Post-job cleanup..."
          docker system prune -f || true
          rm -f frontend.tar.gz || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            echo "TAG_SUFFIX=$VERSION_TAG" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG_SUFFIX=$LATEST_TAG" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.TAG_SUFFIX }}

      - name: Save and compress frontend Docker image
        run: |
          # Remove any existing tar file
          rm -f frontend.tar.gz || true
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-frontend:${{ env.TAG_SUFFIX }} | gzip > frontend.tar.gz
        continue-on-error: true

      - name: Upload frontend image tar
        uses: actions/upload-artifact@v4
        if: success() && hashFiles('frontend.tar.gz') != ''
        with:
          name: frontend-image-${{ github.run_id }}-${{ github.run_attempt }}
          path: frontend.tar.gz
          retention-days: 7

  build-and-push-backend:
    runs-on: [b1]
    environment: ${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}
    steps:
      - name: Force cleanup runner workspace
        run: |
          echo "Force cleaning runner workspace..."
          
          # Clean up any existing artifacts
          rm -f backend1.tar.gz backend2.tar.gz || true
          
          # Clean Docker system
          docker system prune -f || true
          
          # Clean up workspace (only files we own)
          find ${{ github.workspace }} -type f -delete || true
          find ${{ github.workspace }} -type d -empty -delete || true
        continue-on-error: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            echo "TAG_SUFFIX=$VERSION_TAG" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG_SUFFIX=$LATEST_TAG" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "TAG_SUFFIX=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build & Push Backend1
        uses: docker/build-push-action@v6
        with:
          context: ./backend1
          file: ./backend1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }}

      - name: Save and compress backend1 Docker image
        run: |
          # Remove any existing tar file
          rm -f backend1.tar.gz || true
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend1:${{ env.TAG_SUFFIX }} | gzip > backend1.tar.gz
        continue-on-error: true

      - name: Upload backend1 image tar
        uses: actions/upload-artifact@v4
        if: success() && hashFiles('backend1.tar.gz') != ''
        with:
          name: backend1-image-${{ github.run_id }}-${{ github.run_attempt }}
          path: backend1.tar.gz
          retention-days: 7

      - name: Build & Push Backend2
        uses: docker/build-push-action@v6
        with:
          context: ./backend2
          file: ./backend2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }}

      - name: Save and compress backend2 Docker image
        run: |
          # Remove any existing tar file
          rm -f backend2.tar.gz || true
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/fellowship-backend2:${{ env.TAG_SUFFIX }} | gzip > backend2.tar.gz
        continue-on-error: true

      - name: Upload backend2 image tar
        uses: actions/upload-artifact@v4
        if: success() && hashFiles('backend2.tar.gz') != ''
        with:
          name: backend2-image-${{ github.run_id }}-${{ github.run_attempt }}
          path: backend2.tar.gz
          retention-days: 7